package no11;

public class Window extends javax.swing.JFrame {

    /**
     * Creates new form Window
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        plaintext1 = new javax.swing.JTextField();
        chipher1 = new javax.swing.JTextField();
        tombolcaisarEN = new javax.swing.JButton();
        tombolcaisarDE = new javax.swing.JButton();
        tombolhapusCaisar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        caisarkey = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        plain2 = new javax.swing.JTextField();
        cipher2 = new javax.swing.JTextField();
        key2 = new javax.swing.JTextField();
        encript2 = new javax.swing.JButton();
        decript2 = new javax.swing.JButton();
        hapus2 = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 102, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 300));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 153, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 24)); // NOI18N
        jLabel1.setText("CAISAR CIPHER");
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel5.setBackground(new java.awt.Color(255, 204, 255));
        jPanel5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("PLAIN TEXT");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel3.setText("CIPHER TEXT");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        plaintext1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plaintext1ActionPerformed(evt);
            }
        });
        jPanel5.add(plaintext1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 180, -1));

        chipher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chipher1ActionPerformed(evt);
            }
        });
        jPanel5.add(chipher1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 180, -1));

        tombolcaisarEN.setText("ENCRIPT");
        tombolcaisarEN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcaisarENActionPerformed(evt);
            }
        });
        jPanel5.add(tombolcaisarEN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, -1));

        tombolcaisarDE.setText("DECRIPT");
        tombolcaisarDE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcaisarDEActionPerformed(evt);
            }
        });
        jPanel5.add(tombolcaisarDE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, -1, -1));

        tombolhapusCaisar.setText("CLEAR");
        tombolhapusCaisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusCaisarActionPerformed(evt);
            }
        });
        jPanel5.add(tombolhapusCaisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel4.setText("KEY");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel5.add(caisarkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 180, -1));

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(255, 153, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(500, 40));

        jLabel6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel6.setText("VIGENERE CHIPHER");
        jPanel6.add(jLabel6);

        jPanel2.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        jPanel7.setBackground(new java.awt.Color(255, 204, 255));
        jPanel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("PLAIN TEXT");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        jLabel8.setText("CIPHER TEXT");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel9.setText("KEY");
        jPanel7.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));
        jPanel7.add(plain2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, -1));

        cipher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cipher2ActionPerformed(evt);
            }
        });
        jPanel7.add(cipher2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 180, -1));
        jPanel7.add(key2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 180, -1));

        encript2.setText("ENCRIPT");
        encript2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encript2ActionPerformed(evt);
            }
        });
        jPanel7.add(encript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, -1, -1));

        decript2.setText("DECRIPT");
        decript2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decript2ActionPerformed(evt);
            }
        });
        jPanel7.add(decript2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, -1, -1));

        hapus2.setText("CLEAR");
        hapus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus2ActionPerformed(evt);
            }
        });
        jPanel7.add(hapus2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chipher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chipher1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chipher1ActionPerformed

    private void tombolcaisarENActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcaisarENActionPerformed
        String plainText = plaintext1.getText().toLowerCase();
        int key = Integer.parseInt(caisarkey.getText());
        String encript = caisarEncript(plainText, key);
        chipher1.setText(encript.toUpperCase());
    }//GEN-LAST:event_tombolcaisarENActionPerformed

    private void tombolcaisarDEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcaisarDEActionPerformed
        String encript = chipher1.getText().toLowerCase();
        int key = Integer.parseInt(caisarkey.getText());
        String plainText = caisarDecript(encript, key);
        plaintext1.setText(plainText.toUpperCase());
    }//GEN-LAST:event_tombolcaisarDEActionPerformed

    private void tombolhapusCaisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusCaisarActionPerformed
        plaintext1.setText("");
        chipher1.setText("");
        caisarkey.setText("");
    }//GEN-LAST:event_tombolhapusCaisarActionPerformed

    private void cipher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cipher2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cipher2ActionPerformed

    private void plaintext1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plaintext1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plaintext1ActionPerformed

    private void encript2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encript2ActionPerformed
        String plainText = plain2.getText().toLowerCase();
        String key = key2.getText().toLowerCase();
        String encript = vigenereEncript(plainText, key);
        cipher2.setText(encript.toUpperCase());
    }//GEN-LAST:event_encript2ActionPerformed

    private void decript2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decript2ActionPerformed
        String encript = cipher2.getText().toLowerCase();
        String key = key2.getText().toLowerCase();
        String plainText = vigenereDecript(encript, key);
        plain2.setText(plainText.toUpperCase());
    }//GEN-LAST:event_decript2ActionPerformed

    private void hapus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus2ActionPerformed
        plain2.setText("");
        cipher2.setText("");
        key2.setText("");
    }//GEN-LAST:event_hapus2ActionPerformed

    private static String caisarEncript(String text, int shift) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < text.length(); i++) {
            int p = text.charAt(i) - 97;
            int e = (p + shift) % 26;
            char huruf = (char) (e + 97);
            sb.append(huruf);
        }
        return sb.toString();
    }

    private static String caisarDecript(String text, int shift) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < text.length(); i++) {
            int e = text.charAt(i) - 97;
            int p = (e - shift) % 26;
            if (p < 0) {
                p += 26;
            }
            char huruf = (char) (p + 97);
            sb.append(huruf);
        }
        return sb.toString();
    }

    private static String vigenereEncript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        int panjang = text.length();
        for (int i = 0; i < panjang; i++) {
            int j = i%shift.length();
            int k = (int) shift.charAt(j) -97;
            int p = text.charAt(i)-97;
            int e = (p+k)%26;
            char huruf = (char)(e+97);
            sb.append(huruf);
        }
        return sb.toString();
        
    } 
    
    private static String vigenereDecript(String text, String shift){
        StringBuffer sb = new StringBuffer();
        int panjang = text.length();
        for (int i = 0; i < panjang; i++) {
            int j = i%shift.length();
            int k = (int) shift.charAt(j) -97;
            int p = text.charAt(i)-97;
            int e = (p-k)%26;
            if (e<0) {
                e+=26;
            }
            char huruf = (char)(e+97);
            sb.append(huruf);
        }
        return sb.toString();
        
    }
            
            /**
             * @param args the command line arguments
             */

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField caisarkey;
    private javax.swing.JTextField chipher1;
    private javax.swing.JTextField cipher2;
    private javax.swing.JButton decript2;
    private javax.swing.JButton encript2;
    private javax.swing.JButton hapus2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField key2;
    private javax.swing.JTextField plain2;
    private javax.swing.JTextField plaintext1;
    private javax.swing.JButton tombolcaisarDE;
    private javax.swing.JButton tombolcaisarEN;
    private javax.swing.JButton tombolhapusCaisar;
    // End of variables declaration//GEN-END:variables
}
